export const AUTH_QUERY_KEYS = {
    TOKEN: "TOKEN",
    USER: "USER",
    DEVICE_UUID: "DEVICE_UUID",
    GET_ME: "GET_ME",
    AUTH: "AUTH",
    NOTIFICATION_LISTING: "NOTIFICATION_LISTING",
    NOTIFICATION_UNREAD_COUNT: "NOTIFICATION_UNREAD_COUNT",
    CHATS: "CHATS"
} as const;

export default AUTH_QUERY_KEYS;
