export const WALLET_QUERY_KEYS = {
    CONFIG: "WALLET_CONFIG",
    SETUP_INTENT: "WALLET_SETUP_INTENT",
    PAYMENT_METHODS: "WALLET_PAYMENT_METHODS",
    PAY_ORDER: "WALLET_PAY_ORDER",
} as const;

export default WALLET_QUERY_KEYS;
