export const SHIPMENT_QUERY_KEYS = {
    SHIPMENTS: "SHIPMENTS",
    SHIPMENT: "SHIPMENT",
    SHIPMENT_STATUS: "SHIPMENT_STATUS",
    ANALYTICS: "SHIPMENT_ANALYTICS",
} as const;

export default SHIPMENT_QUERY_KEYS;
