import { Select } from "@/components/custom/Select";
import TextareaInput from "@/components/custom/Inputs/TextareaInput/TextareaInput";
import { type FieldType } from "@/components/custom/Form";
import { type ManageShipmentFormValues } from "./ManageShipment.schema";
import { CARRIER_OPTIONS } from "@/constants/shipment-status.constants";
import { COUNTRY_OPTIONS } from "@/constants/order-status.constants";

export const MANAGE_SHIPMENT_FORM_CONFIG: FieldType<ManageShipmentFormValues>[] =
    [
        {
            name: "orderId",
            label: "Order ID",
            type: "text",
            placeholder: "e.g. ORD-7842",
            required: true,
            className: "col-span-12 md:col-span-6",
            labelClass: "font-normal",
        },
        {
            name: "customerName",
            label: "Customer Name",
            type: "text",
            placeholder: "e.g. Alex Johnson",
            required: true,
            className: "col-span-12 md:col-span-6",
            labelClass: "font-normal",
        },
        {
            name: "customerEmail",
            label: "Email Address",
            type: "email",
            placeholder: "e.g. alex@example.com",
            required: true,
            className: "col-span-12 md:col-span-6",
            labelClass: "font-normal",
        },
        {
            name: "carrier",
            label: "Carrier",
            component: Select,
            placeholder: "Select carrier",
            required: true,
            className: "col-span-12 md:col-span-6",
            componentProps: {
                options: CARRIER_OPTIONS,
                labelRequired: true,
                labelClass: "font-normal",
            },
        },
        {
            name: "trackingNumber",
            label: "Tracking Number",
            type: "text",
            placeholder: "e.g. 1Z999AA10123456790",
            required: true,
            className: "col-span-12 md:col-span-6",
            labelClass: "font-normal",
        },
        {
            name: "weight",
            label: "Weight (kg)",
            type: "number",
            placeholder: "e.g. 1.5",
            required: true,
            className: "col-span-12 md:col-span-6",
            labelClass: "font-normal",
        },
        {
            name: "originStreet",
            label: "Origin Street Address",
            type: "text",
            placeholder: "e.g. 100 Warehouse Blvd",
            required: true,
            className: "col-span-12",
            labelClass: "font-normal",
        },
        {
            name: "originCity",
            label: "Origin City",
            type: "text",
            placeholder: "e.g. San Jose",
            required: true,
            className: "col-span-12 md:col-span-6",
            labelClass: "font-normal",
        },
        {
            name: "originZip",
            label: "Origin ZIP / Postal Code",
            type: "text",
            placeholder: "e.g. 95110",
            required: true,
            className: "col-span-12 md:col-span-6",
            labelClass: "font-normal",
        },
        {
            name: "originState",
            label: "Origin State / Province",
            type: "text",
            placeholder: "e.g. CA",
            required: true,
            className: "col-span-12 md:col-span-6",
            labelClass: "font-normal",
        },
        {
            name: "originCountry",
            label: "Origin Country",
            component: Select,
            placeholder: "Select country",
            required: true,
            className: "col-span-12 md:col-span-6",
            componentProps: {
                options: COUNTRY_OPTIONS,
                labelRequired: true,
                labelClass: "font-normal",
            },
        },
        {
            name: "destinationStreet",
            label: "Destination Street Address",
            type: "text",
            placeholder: "e.g. 142 Maple Drive",
            required: true,
            className: "col-span-12",
            labelClass: "font-normal",
        },
        {
            name: "destinationCity",
            label: "Destination City",
            type: "text",
            placeholder: "e.g. San Francisco",
            required: true,
            className: "col-span-12 md:col-span-6",
            labelClass: "font-normal",
        },
        {
            name: "destinationZip",
            label: "Destination ZIP / Postal Code",
            type: "text",
            placeholder: "e.g. 94105",
            required: true,
            className: "col-span-12 md:col-span-6",
            labelClass: "font-normal",
        },
        {
            name: "destinationState",
            label: "Destination State / Province",
            type: "text",
            placeholder: "e.g. CA",
            required: true,
            className: "col-span-12 md:col-span-6",
            labelClass: "font-normal",
        },
        {
            name: "destinationCountry",
            label: "Destination Country",
            component: Select,
            placeholder: "Select country",
            required: true,
            className: "col-span-12 md:col-span-6",
            componentProps: {
                options: COUNTRY_OPTIONS,
                labelRequired: true,
                labelClass: "font-normal",
            },
        },
        {
            name: "notes",
            label: "Shipment Notes",
            component: TextareaInput,
            placeholder: "Any special handling instructions or notes…",
            required: false,
            className: "col-span-12",
            componentProps: {
                rows: 3,
                maxLength: 500,
                showCharacterCount: true,
            },
        },
    ];
