export const PRODUCT_QUERY_KEYS = {
    PRODUCTS: "PRODUCTS",
    PRODUCT: "PRODUCT",
    ANALYTICS: "PRODUCT_ANALYTICS",
    PRODUCT_MONTHLY_SALES: "PRODUCT_MONTHLY_SALES",
    PRODUCT_CUSTOMER_REVIEWS: "PRODUCT_CUSTOMER_REVIEWS",
} as const;

export default PRODUCT_QUERY_KEYS;
